In [6]:
import os
import pandas as pd

import librosa
import librosa.display

import numpy as np

from keras.utils import np_utils

from matplotlib import pyplot as plt

from sklearn import metrics 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

import pickle


In [2]:
def getData():
    df = pd.read_csv('input/train.csv')

    Classes = df.Class.unique().tolist()
    y = []
    X = []; yp = []; new_X = []
    for i in df.ID:
        new, rate = librosa.load('input/train/Train/%d.wav'%i)
        mfccs = np.mean(librosa.feature.mfcc(y=new, sr=rate, n_mfcc=200).T, axis = 0)
        idx = Classes.index(df[df.ID == i]['Class'].tolist()[0])
        yp.append(idx)
        new_X.append(mfccs)
    return new_X, yp

In [4]:

NewX, y = getData()


In [8]:


X_Train, X_Test, Y_Train, Y_Test = train_test_split(NewX, y, test_size=0.10, shuffle = True)

clf = RandomForestClassifier(n_estimators = 200)
clf.fit(X_Train, Y_Train)

print(clf.score(X_Test, Y_Test))



0.9099264705882353


In [14]:
filename = 'finalized_model.sav'
df = pd.read_csv('input/train.csv')
Classes = df.Class.unique().tolist()


In [10]:
pickle.dump(clf, open(filename, 'wb'))

In [11]:

loaded_model = pickle.load(open(filename, 'rb'))



In [12]:
testResult = loaded_model.score(X_Test, Y_Test)
trainResult = loaded_model.score(X_Train, Y_Train)

In [17]:
print(f"{testResult*len(X_Test)}/{len(X_Test)} {testResult}%")
print(f"{trainResult*len(X_Train)}/{len(X_Train)} {trainResult}%")


#Gets the probabilities of each value
print(loaded_model.predict_proba(X_Train))
print(Classes)




495.0/544 0.9099264705882353%
4891.0/4891 1.0%
[[0.025 0.03  0.01  ... 0.01  0.    0.005]
 [0.005 0.045 0.015 ... 0.005 0.    0.005]
 [0.02  0.025 0.015 ... 0.04  0.025 0.   ]
 ...
 [0.015 0.02  0.    ... 0.805 0.01  0.005]
 [0.11  0.025 0.005 ... 0.025 0.015 0.005]
 [0.005 0.02  0.    ... 0.905 0.01  0.   ]]
['siren', 'street_music', 'drilling', 'dog_bark', 'children_playing', 'gun_shot', 'engine_idling', 'air_conditioner', 'jackhammer', 'car_horn']
